### ISSUE TITLE
Recognize classes types by the abstract they extend rather than by name/prefix

### ISSUE THREAD

**Issue by Tito-Kati** [gacela-project/gacela#105]
Gacela does a good job of helping to decouple the domain from everything else but is nonetheless coupled with the verbosity of the names of the classes that extend its abstracts.

It would be great if Gacela detects classes by the abstract they extend instead of by their name/prefix.

An example where this would be beneficial is if Gacela was used in a large project and suddenly the team decided to change the nomenclature of their "Gacela classes".

If the framework recognized the classes in this way, a progressive refactor strategy could be adopted instead of having to do all the work at once to apply the new names.

What do you think?

**Comment by Chemaclass** [comment]
With this https://github.com/gacela-project/gacela/pull/106 now we'll be able to define multiple suffixes for gacela resolvable types. A follow up issue it could be to scan the module directory and look for the class that it's extending certain `...Abtract` class, and then pick the right one.

The biggest problem/complexity I see with this approach is the fact of scanning the directories and doing so much parsing in order to find the proper classes... This could be a big downside for the performance. For this reason, I wanted to first develop this concept (of explicitly allowing multiple suffixes that you have to know in advance; so you can write them down in gacela.php) and then the other thing could be postpone or even reconsider.
